### ISSUE TITLE
Quick start does not work on Windows machine

### ISSUE THREAD

**Issue by KyleSiler** [njenan/turbulence#1]
```

module.js:327
    throw err;
    ^

Error: Cannot find module 'C:UserskylesiAppDataRoaming
pm
ode_modules     urbulence/src/Turbulence'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at new require (internal/module.js:12:17)
    at eval (eval at <anonymous> (C:\Users\kylesi\AppData\Roaming\npm\node_modules\turbulence\index.js:24:128), <anonymous>:1:9)
    at Object.<anonymous> (C:\Users\kylesi\AppData\Roaming\npm\node_modules\turbulence\index.js:18:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by njenan** [comment]
Looks like this was related to some usages of `__dirname` while requiring dependency in the index.js file.  I've just pushed a new version that should resolve these issues.  Unfortunately travis-ci does not support windows executors (yet) so I'll have to figure out another way of guarding against regressions.
